export const COMPANY_PERMISSIONS = {
  COMPANY_VIEW: "COMPANY_VIEW",
  COMPANY_CREATE: "COMPANY_CREATE",
  COMPANY_EDIT: "COMPANY_EDIT",
  COMPANY_APPROVE: "COMPANY_APPROVE",
  COMPANY_ACTIVATE: "COMPANY_ACTIVATE",
} as const;

export type CompanyPermission = typeof COMPANY_PERMISSIONS[keyof typeof COMPANY_PERMISSIONS];


